#!/usr/bin/env bash
################################################################################
#
# Magma-UT
# Copyright (C) 2020 Ulrich Thiel
# Licensed under GNU GPLv3, see COPYING.
# https://github.com/ulthiel/magma-ut
# thiel@mathematik.uni-kl.de, https://ulthiel.com/math
#
# Run selfcheck on a package. This is quite a nice and generic script actually.
#
# Run ./selfcheck -p=PACKAGE_NAME (SELFCHECK1 SELFCHECK2 ...)
#
# e.g.
#
# ./selfcheck -p=Magma-UT Files MD5 Strings
#
# Running
#
# ./selfcheck -p=Magma-UT
#
# runs all selfchecks.
#
# This script needs to be started from this folder to not mess up paths.
# It will then load the files given as arguments into Magma and
# report any errors, also things like when a command didn't exist.
#
# The Magma session is initialized with logging enabled and the logfile
# will be parsed afterwards. Also SetQuitOnError is activated. When the
# keyword "error" is found in the log, this will be reported.
#
# You should write your selfchecks in a way that it throws errors when
# something is not correct. You can e.g. use
#
# assert X eq Y;
#
# Is then X is not equal to X, this throws an error. You should look at the
# examples provided.
#
################################################################################

# First, make sure this script is run from the Selfcheck directory.
# I need this to have less fiddling below.
if [ ! -f "../../magma-ut" ]; then
  echo Error: you need to run this script directly from the Tools/Selfcheck directory.
  exit 1
fi

# Parse arguments
# Cheers to https://pretzelhands.com/posts/command-line-flags
for arg in "$@"
do
  case $arg in
    -r|--report)
    REPORT=YES
    shift # Remove --initialize from processing
    ;;
    -p=*|--package=*)
    PACKAGE="${arg#*=}"
    shift # Remove --package= from processing
    ;;
    *)
    SELFCHECKS="$SELFCHECKS $1"
    shift # Remove generic argument from processing
    ;;
  esac
done

# Check if package specified
if [ -z ${PACKAGE+x} ]; then
  echo "Please specify package to selfcheck with -p= option."
  exit 1
fi

# If no selfcheck files given, take all of them
if [ -z ${SELFCHECKS+x} ]; then
  cd ../../Packages/$PACKAGE/Selfchecks/
  SELFCHECKS=`(echo *.m)`
  cd ../../../Tools/Selfcheck
fi

# Gather some system information for reporting
if [ "$REPORT" == "YES" ]; then

  HOST=`uname -n`

  #Determine OS version
  osrough=`uname -s`
  if [ "$osrough" == "Darwin" ]; then
    #Mac OS
    OS=`sw_vers -productName`
    VER=`sw_vers -productVersion`
  elif [ -f /etc/os-release ]; then
    # freedesktop.org and systemd
    . /etc/os-release
    OS=$NAME
    VER=$VERSION_ID
  elif type lsb_release >/dev/null 2>&1; then
    # linuxbase.org
    OS=$(lsb_release -si)
    VER=$(lsb_release -sr)
  elif [ -f /etc/lsb-release ]; then
    # For some versions of Debian/Ubuntu without lsb_release command
    . /etc/lsb-release
    OS=$DISTRIB_ID
    VER=$DISTRIB_RELEASE
  elif [ -f /etc/debian_version ]; then
    # Older Debian/Ubuntu/etc.
    OS=Debian
    VER=$(cat /etc/debian_version)
  else
    # Fall back to uname
    OS=$(uname -s)
    VER=$(uname -r)
  fi
  OS_VER="$OS $VER"

  #CPU
  if [ "$osrough" == "Darwin" ]; then
  CPU=`sysctl -n machdep.cpu.brand_string`
  else
  CPU=`cat /proc/cpuinfo | grep 'model name' | tail -n 1 | awk -v FS=': ' '{print $2}'`
  fi

  # curl or wget?
  if command -v "curl" >/dev/null 2>&1; then
    DWN_TOOL="curl"
  elif command -v "wget" >/dev/null 2>&1; then
    DWN_TOOL="wget"
  else
    echo "Error: Neither curl nor wget found."
    exit 1
  fi

  #Magma-UT version
  git describe >/dev/null 2>/dev/null
  if [ $? -eq 0 ]; then
    MAGMA_UT_VER=`git describe`
  else
    cat ../../version.txt >/dev/null 2>/dev/null
    if [ $? -eq 0 ]; then
      MAGMA_UT_VER=`cat ../../version.txt`
    fi
  fi
fi

# Create Log directory
mkdir -p Log

# Determine maximal length of file name for nice printing
MAXLEN=0
for f in $SELFCHECKS; do
  NAME=${f##*/}
  NAME=${NAME%.m}
  len=${#NAME}
  if [ "$len" -gt "$MAXLEN" ]; then
    MAXLEN=$len
  fi
done

MAXLEN=$((MAXLEN + 2))

# Now, go through the selfchecks
for f in $SELFCHECKS; do

  NAME=${f##*/}
  NAME=${NAME%.m}
  DATE=`date -u +"%Y-%m-%d %H:%M:%S"`

  printf "%-${MAXLEN}s" $NAME

  touch Log/$NAME.lck

  # This is the initial Magma code to start and report the selfcheck
  INIT=$(cat << END
SetAssertions(1);
SetQuitOnError(true);
AttachSpec("../../Packages/$PACKAGE/$PACKAGE.s.m");
printf "MAGMA_UT_SELFCHECK_MAGMA=%o\n", GetVersionString();
MAGMA_UT_SELFCHECK_TIME := Cputime();
assert FileExists("../../Packages/$PACKAGE/Selfchecks/$NAME.m");
load "../../Packages/$PACKAGE/Selfchecks/$NAME.m";
printf "MAGMA_UT_SELFCHECK_TIME=%o\n", Cputime(MAGMA_UT_SELFCHECK_TIME);
printf "MAGMA_UT_SELFCHECK_MEM=%o\n", Round(GetMemoryUsage()/1000^2);
DeleteFile("Log/$NAME.lck");
quit;
END
  )

  rm -f Log/$NAME.log >/dev/null 2>&1

  echo "$INIT" | ../../magma-ut >Log/$NAME.log 2>&1

  RES=$?

  grep -q -i "error" "Log/$NAME.log"

  RESULT=0

  if [ -f Log/$NAME.lck ] || [ ! $RES -eq 0 ] || [ $? -eq 0 ]; then
    RESULT=1
    echo -e "\033[31;5;7mFAILED\033[0m"
  else
    TIME=`grep MAGMA_UT_SELFCHECK_TIME "Log/$NAME.log" | awk -F'=' '{print $2}'`
    MEM=`grep MAGMA_UT_SELFCHECK_MEM "Log/$NAME.log" | awk -F'=' '{print $2}'`
    echo -e "\033[0;32mOK\033[0m  ${TIME}s\t${MEM}MB"
  fi

  MAGMA_VER=`grep MAGMA_UT_SELFCHECK_MAGMA "Log/$NAME.log" | awk -F'=' '{print $2}'`

done

exit 0
